---
title: "wordle.Rmd"
output: html_document
date: "2024-02-12"
---
### Step 1
```{r}
load_dictionary <- function(filename){ 
  #Creating function with single argument, "filename"
  library(readr) 
  #Loading {readr} so I can read in .txt from https:// filename
   f <- filename 
   #f should be https:// filename
   d <- read_tsv(f, col_names = TRUE) 
   #Creating dataframe from .txt file
   return(d$words) 
   #Creating vector from "words" column (column name of single column in both .txt files)
}

valid_list <- load_dictionary("https://raw.githubusercontent.com/jamiewiener119/exercise-04/main/collins-scrabble-words-2019.txt") 
#Creating vector, valid_list, of valid words to guess
solution_list <- load_dictionary("https://raw.githubusercontent.com/jamiewiener119/exercise-04/main/google-10000-english-usa-no-swears.txt") 
#Creating vector, solution_list, of possible solution words

str(valid_list) #Checking if above was successful
str(solution_list)
```

### Step 2
```{r}
solution_list <-intersect(valid_list,solution_list) 
#Winnowing solution_list to only include words that are included in valid_list
#Rather than 9884 words, the updated solution_list only contains 8336 words
```


### Step 3
```{r}
pick_solution <- function(solution_list){ 
  #Creating function with single argument, "solution_list"
  library(stringr) #Loading {stringr} because using str_length()
  five_letter_solution <- solution_list[str_length(solution_list)==5] #Creating vector five_letter_solution, which is a subset of solution_list containing only entries (words) with a computed length of 5 codepoints (letters)
  w <- sample(five_letter_solution, size = 1, replace = FALSE, prob = NULL) #Assigning one randomly sampled word from five_letter_solution (without replacement or weighted probabilities) to variable, w
  return(strsplit(w,"")) 
  #Have function return string in variable w split into individual codepoints (letters)
}

pick_solution(solution_list) #Checking if above was successful

solution <- pick_solution(solution_list) 
#Assigning result of function to new variable, solution
```
### Step 4
```{r}
play_wordle <- function(solution){
  library(dplyr) 
  library(insight) #To use print_color()
  print("WELCOME! YOU HAVE 6 CHANCES TO GUESS THE 5-LETTER WORD.")
  guess <- strsplit(toupper(readline("ENTER YOUR GUESS HERE, THEN PRESS <ENTER>: ")),"")
  evaluate_guess <- function(guess,solution){
  if (setequal(guess[[1]][1],solution[[1]][1])==TRUE){
  print_color(guess[[1]][1],"green")
  } else {
    if ((any(solution==guess[[1]][1]))==TRUE){
      print_color(guess[[1]][1],"yellow")
    } else {
    print_color(guess[[1]][1],"red")
  }}
   if (setequal(guess[[1]][2],solution[[1]][2])==TRUE){
  print_color(guess[[1]][2],"green")
  } else {
    if ((any(solution==guess[[1]][2]))==TRUE){
      print_color(guess[[1]][2],"yellow")
    } else {
    print_color(guess[[1]][2],"red")
  }}
  if (setequal(guess[[1]][3],solution[[1]][3])==TRUE){
  print_color(guess[[1]][3],"green")
  } else {
    if ((any(solution==guess[[1]][3]))==TRUE){
      print_color(guess[[1]][3],"yellow")
    } else {
    print_color(guess[[1]][3],"red")
  }}
    if (setequal(guess[[1]][4],solution[[1]][4])==TRUE){
  print_color(guess[[1]][4],"green")
  } else {
    if ((any(solution==guess[[1]][4]))==TRUE){
      print_color(guess[[1]][4],"yellow")
    } else {
    print_color(guess[[1]][4],"red")
  }}
    if (setequal(guess[[1]][5],solution[[1]][5])==TRUE){
  print_color(guess[[1]][5],"green")
  } else {
    if ((any(solution==guess[[1]][5]))==TRUE){
      print_color(guess[[1]][5],"yellow")
    } else {
    print_color(guess[[1]][5],"red")
    }}
  if (setequal(guess,solution)==TRUE){
    print("YOU WIN :)")
  } else {
    print("SORRY! THAT'S NOT IT.")
    play_wordle(solution)
  }
    return(setdiff(LETTERS,guess))}
  return(evaluate_guess(guess,solution))
}
play_wordle(solution)
```

